<a href="https://colab.research.google.com/github/npppp9494/np/blob/main/Lab04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy -  multidimensional data arrays

<a target="_blank" href="https://colab.research.google.com/github/hariseldon99/msph306/blob/main/Lab04.ipynb"> <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction

The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python.

To use `numpy` you need to import the module, using for example:

In [1]:
import numpy as np

Here, we have imported the numpy module into its own namespace in our programs. We have chosen to call this namespace `np`, which is the standard rule for using `numpy`, but any name will do, in principle.

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*.



## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [2]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [3]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3, 4]])

M

array([[1, 2],
       [3, 4]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [4]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [5]:
v.shape

(4,)

In [6]:
M.shape

(2, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [7]:
M.size

4

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument:

In [8]:
M = np.array([[1, 2], [3, 4]], dtype=complex)

M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Note that python uses 'j' to denote $\sqrt{-1}$ instead of the usual $i$. This is so that programmers can use the letter 'i' for other things. Complex numbers can be handled seamlessly in python.

### Exercise 01:

   1. In the code cell below, create a list of the numbers $1,2,3,4, \dots 10,000$ and call it 'a'. Then, Convert it to a numpy array and use array programming to multiply all the numbers by $2$ and output the result.
   2. Use the code cell below and use numpy to build the three Pauli matrices. use the 'print()' function to show the output.

### Using array-generating functions

For larger arrays it is impractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

#### arange

In [9]:
# create a range
x = np.arange(0, 24, 1) # arguments: start, stop, step
display(x)

y = np.arange(9)
display(y)

z = np.arange(0, 20, 2)
display(z)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

**Note:** This function is called 'a-range' (the letter 'a' followed by 'range') and typed `arange` (with a single 'r'). **It is not called `arrange`** (with two 'r's), a common mistake.

The linspace() and logspace() functions create uniformly spaced list of numbers on a line. The first function does it on a linear scale, and the second function on a log-scale.

In [10]:
# using linspace, both end points ARE included
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [11]:
np.logspace(0, 10, 10, base=np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

### Exercise 02:

1. Using numpy, create a list of all even numbers from $1 - 100$. Also, create a list of all odd numbers in the same range, as well as a list of multiples of $4$.
2. Create an array of $100$ uniformly spaced numbers in the interval $\left[-\pi , \pi\right]$.  The value of $\pi$ can be gotten from `np.pi`.

### The diag function:

The `np.diag()` function can be used to create a matrix and populate it with a given vector along a desired diagonal.

In [12]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [13]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

With the diag function we can also extract the diagonal and subdiagonals of an array:

In [14]:
A = np.random.rand(3,3)
A

array([[0.9479991 , 0.44950798, 0.0396493 ],
       [0.15473787, 0.11133371, 0.53802929],
       [0.93361522, 0.4110315 , 0.589889  ]])

In [15]:
np.diag(A)

array([0.9479991 , 0.11133371, 0.589889  ])

In [16]:
np.diag(A, k=-1)

array([0.15473787, 0.4110315 ])

### Arrays of zeros and ones

Homogeneous arrays (where all the values are the same) of any size and shape can be easily created.

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

We can combine multiple functions to create more complex arrays.

In [21]:
#Diagonal matrix with ones on the superdiagonal
np.diag(np.ones(3), k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
#Diagonal matrix with twos on the subdiagonal
np.diag(2 * np.ones(3), k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.]])

### Exercise 03:

Prepare a $7 \times 7$ matrix with fixed numbers ($5$) on the $2^{nd}$ superdiagonal and subdiagonal.

## Manipulating arrays

### Indexing

We can index elements in an array using square brackets and indices:

In [23]:
v = np.random.random(10) # 10 random numbers from a uniform distribution in [0,1]
print(v)
# v is a vector, and has only one dimension, taking one index
v[0]

[0.84412995 0.25502548 0.99895859 0.68571798 0.65296403 0.66464546
 0.8298869  0.99776223 0.71687697 0.69793243]


np.float64(0.8441299531543071)

In [24]:
M = np.random.random((4,4))  # M is a 4 X 4 matrix, or a 2 dimensional array, taking two indices
print(M)

M[1,1]

[[0.10418635 0.511333   0.96932276 0.10775221]
 [0.44829356 0.52794236 0.70036472 0.75719543]
 [0.97002059 0.54918177 0.79991354 0.55198701]
 [0.88647752 0.77385855 0.52217127 0.16265709]]


np.float64(0.5279423554340136)

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array)

In [25]:
M

array([[0.10418635, 0.511333  , 0.96932276, 0.10775221],
       [0.44829356, 0.52794236, 0.70036472, 0.75719543],
       [0.97002059, 0.54918177, 0.79991354, 0.55198701],
       [0.88647752, 0.77385855, 0.52217127, 0.16265709]])

In [26]:
M[1]

array([0.44829356, 0.52794236, 0.70036472, 0.75719543])

The same thing can be achieved with using `:` instead of an index:

In [27]:
M[1,:] # row 1

array([0.44829356, 0.52794236, 0.70036472, 0.75719543])

In [28]:
M[:,1] # column 1

array([0.511333  , 0.52794236, 0.54918177, 0.77385855])

We can assign new values to elements in an array using indexing:

In [29]:
M[0,0] = 1

In [30]:
M

array([[1.        , 0.511333  , 0.96932276, 0.10775221],
       [0.44829356, 0.52794236, 0.70036472, 0.75719543],
       [0.97002059, 0.54918177, 0.79991354, 0.55198701],
       [0.88647752, 0.77385855, 0.52217127, 0.16265709]])

In [31]:
# also works for rows and columns
M[1,:] = 0
M[:,2] = -1

In [32]:
M

array([[ 1.        ,  0.511333  , -1.        ,  0.10775221],
       [ 0.        ,  0.        , -1.        ,  0.        ],
       [ 0.97002059,  0.54918177, -1.        ,  0.55198701],
       [ 0.88647752,  0.77385855, -1.        ,  0.16265709]])

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [33]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [34]:
A[1:3]

array([2, 3])

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [35]:
A[1:3] = [-2,-3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[lower:upper:step]`:

In [36]:
A[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [37]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [38]:
A[:3] # first three elements

array([ 1, -2, -3])

In [39]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [40]:
A = np.array([1,2,3,4,5])

In [41]:
A[-1] # the last element in the array

np.int64(5)

In [42]:
A[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [43]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [44]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [45]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

#### An important point to remember
So, array slices work more-or-less like slices of python lists or strings. There is, however, one key difference.

With lists (or strings, tuples), each slice is a copy. However, slices of `NumPy` arrays are different. These slices are actually **views** on the original array. `Numpy` is designed to be memory-efficient and does not make unnecessary copies.

What this means is that changing the slice of an array **actually changes** the original array.

In [46]:
G = np.array([[n+m*10 for n in range(5)] for m in range(5)])
print(G)

G[:,1] = np.arange(5) #I changed the second column of G by taking the slice of the second column and assigning it a new value
print(G) #The original array G has been modified

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[[ 0  0  2  3  4]
 [10  1 12 13 14]
 [20  2 22 23 24]
 [30  3 32 33 34]
 [40  4 42 43 44]]


In [47]:
y = G[2] #y is a slice consisting of the third row of G

print(y)

y[2] = 21347 #I changed the third element of y to 21347

print(y) #The slice y has been modified

print(G) #The original array G has ALSO been modified

[20  2 22 23 24]
[   20     2 21347    23    24]
[[    0     0     2     3     4]
 [   10     1    12    13    14]
 [   20     2 21347    23    24]
 [   30     3    32    33    34]
 [   40     4    42    43    44]]


If you want to make a copy of an array in order to fiddle with it without damaging the original data, you can use the `copy()` method.

In [48]:
G = np.array([[n+m*10 for n in range(5)] for m in range(5)])
print(G)

H = G.copy() #This is a COPY of the array G. A new array, with a new memory address, has been created.

H[1] = np.arange(5, 10) #I changed the second row of H by taking the slice of the second row and assigning it a new value
print(H) #The array H has been modified

print(G) #The original array G has NOT been modified

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


Here's something interesting. We can use index slicing to extract diagonals and anti-diagonals of a matrix.

In [49]:
A = np.random.rand(5,5)
A

array([[0.94946943, 0.72919423, 0.71507317, 0.38259496, 0.85260473],
       [0.73091115, 0.46113308, 0.55920603, 0.95021963, 0.97816168],
       [0.79629088, 0.71921003, 0.78877752, 0.96265765, 0.34929059],
       [0.19474225, 0.27742488, 0.49543657, 0.49508531, 0.40229766],
       [0.36459873, 0.04469886, 0.62619834, 0.51967917, 0.83695826]])

In [50]:
#Extract diagonal
A[::-1,::-1]

array([[0.83695826, 0.51967917, 0.62619834, 0.04469886, 0.36459873],
       [0.40229766, 0.49508531, 0.49543657, 0.27742488, 0.19474225],
       [0.34929059, 0.96265765, 0.78877752, 0.71921003, 0.79629088],
       [0.97816168, 0.95021963, 0.55920603, 0.46113308, 0.73091115],
       [0.85260473, 0.38259496, 0.71507317, 0.72919423, 0.94946943]])

**Fancy indexing** is the name for when an array or list is used in-place of an index:

In [51]:
row_indices = [1, 2, 3]
A[row_indices]

array([[0.73091115, 0.46113308, 0.55920603, 0.95021963, 0.97816168],
       [0.79629088, 0.71921003, 0.78877752, 0.96265765, 0.34929059],
       [0.19474225, 0.27742488, 0.49543657, 0.49508531, 0.40229766]])

In [52]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([0.46113308, 0.78877752, 0.40229766])

### Exercise 04:

Execute the cell below to create the $3 \times 4 \times 4$ array named 'data', which is an array of three $4\times 4$ matrices.

In [53]:
data = np.array([[[ 1.,  2.,  3.,  4.],
                [ 5.,  6.,  7.,  8.],
                [ 9., 10., 11., 12.],
                [13., 14., 15., 16.]],

                [[17., 18., 19., 20.],
                [21., 22., 23., 24.],
                [25., 26., 27., 28.],
                [29., 30., 31., 32.]],

                [[33., 34., 35., 36.],
                [37., 38., 39., 40.],
                [41., 42., 43., 44.],
                [45., 46., 47., 48.]]])

Now, index or slice this array to obtain the following:

1. $20.0$
2. The array $\left[9.10,11,12\right]$
3. The following square matrix
   \begin{pmatrix}
   33 & 34 & 35 & 36\\
   37 & 38 & 39 & 40\\
   41 & 42 & 43 & 44\\
   45 & 46 & 47 & 48
   \end{pmatrix}
4. The following sub-matrix
   \begin{pmatrix}
   18 & 19 \\
   22 & 23
   \end{pmatrix}

## Linear Algebra with arrays
As we have seen above, **vectorizing code** is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [54]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [55]:
v1 * 2

array([0, 2, 4, 6, 8])

In [56]:
v1 + 2

array([2, 3, 4, 5, 6])

In [57]:
print(A)
A * 2, A + 2

[[0.94946943 0.72919423 0.71507317 0.38259496 0.85260473]
 [0.73091115 0.46113308 0.55920603 0.95021963 0.97816168]
 [0.79629088 0.71921003 0.78877752 0.96265765 0.34929059]
 [0.19474225 0.27742488 0.49543657 0.49508531 0.40229766]
 [0.36459873 0.04469886 0.62619834 0.51967917 0.83695826]]


(array([[1.89893886, 1.45838847, 1.43014634, 0.76518992, 1.70520946],
        [1.46182229, 0.92226617, 1.11841207, 1.90043925, 1.95632337],
        [1.59258175, 1.43842007, 1.57755505, 1.92531531, 0.69858118],
        [0.3894845 , 0.55484977, 0.99087315, 0.99017061, 0.80459531],
        [0.72919747, 0.08939771, 1.25239668, 1.03935833, 1.67391651]]),
 array([[2.94946943, 2.72919423, 2.71507317, 2.38259496, 2.85260473],
        [2.73091115, 2.46113308, 2.55920603, 2.95021963, 2.97816168],
        [2.79629088, 2.71921003, 2.78877752, 2.96265765, 2.34929059],
        [2.19474225, 2.27742488, 2.49543657, 2.49508531, 2.40229766],
        [2.36459873, 2.04469886, 2.62619834, 2.51967917, 2.83695826]]))

### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [58]:
print(A)
A * A # element-wise multiplication

[[0.94946943 0.72919423 0.71507317 0.38259496 0.85260473]
 [0.73091115 0.46113308 0.55920603 0.95021963 0.97816168]
 [0.79629088 0.71921003 0.78877752 0.96265765 0.34929059]
 [0.19474225 0.27742488 0.49543657 0.49508531 0.40229766]
 [0.36459873 0.04469886 0.62619834 0.51967917 0.83695826]]


array([[0.9014922 , 0.53172423, 0.51132964, 0.1463789 , 0.72693482],
       [0.5342311 , 0.21264372, 0.31271139, 0.90291734, 0.95680028],
       [0.63407916, 0.51726307, 0.62216998, 0.92670976, 0.12200392],
       [0.03792454, 0.07696457, 0.2454574 , 0.24510946, 0.1618434 ],
       [0.13293224, 0.00199799, 0.39212436, 0.27006644, 0.70049912]])

In [59]:
print(v1)
v1 * v1

[0 1 2 3 4]


array([ 0,  1,  4,  9, 16])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [60]:
A.shape, v1.shape

((5, 5), (5,))

In [61]:
A * v1

array([[0.        , 0.72919423, 1.43014634, 1.14778487, 3.41041891],
       [0.        , 0.46113308, 1.11841207, 2.85065888, 3.91264674],
       [0.        , 0.71921003, 1.57755505, 2.88797296, 1.39716236],
       [0.        , 0.27742488, 0.99087315, 1.48525592, 1.60919063],
       [0.        , 0.04469886, 1.25239668, 1.5590375 , 3.34783302]])

### Matrix algebra

What about matrix mutiplication? There are many ways. The simplest way is to use the `@` idiom, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments:

In [62]:
A @ A # Matrix-Matrix product

array([[2.38924064, 1.68714283, 2.37419477, 2.37702561, 2.64007194],
       [2.01800018, 1.45514378, 2.30490928, 2.23491462, 2.47051804],
       [2.22464984, 1.76227704, 2.28942381, 2.40550379, 2.33755419],
       [1.02527762, 0.7815889 , 1.18238335, 1.26923295, 1.14633389],
       [1.28383968, 0.91842655, 1.56121175, 1.47701728, 1.48287133]])

In [63]:
A @ v1 # Matrix-Vector product

array([6.71754436, 8.34285077, 6.58190041, 4.36274457, 6.20396605])

In [64]:
v1 @ v1 # Inner Product (Real vectors)

np.int64(30)

In [65]:
vc = np.array([0 + 1.j, 1 + 2.j, 4 + 3.j, 1 + 5.j, 0])
vc.conjugate() @ vc

np.complex128(57+0j)

In [66]:
vc + A @ v1

array([ 6.71754436+1.j,  9.34285077+2.j, 10.58190041+3.j,  5.36274457+5.j,
        6.20396605+0.j])

The transpose of an array can be obtained with the `.T` method.

In [67]:
A= np.arange(25).reshape(5,5) + (1j) * np.arange(25, 50).reshape(5,5)
print(A)

[[ 0.+25.j  1.+26.j  2.+27.j  3.+28.j  4.+29.j]
 [ 5.+30.j  6.+31.j  7.+32.j  8.+33.j  9.+34.j]
 [10.+35.j 11.+36.j 12.+37.j 13.+38.j 14.+39.j]
 [15.+40.j 16.+41.j 17.+42.j 18.+43.j 19.+44.j]
 [20.+45.j 21.+46.j 22.+47.j 23.+48.j 24.+49.j]]


In [68]:
B = A.T
print(B)

[[ 0.+25.j  5.+30.j 10.+35.j 15.+40.j 20.+45.j]
 [ 1.+26.j  6.+31.j 11.+36.j 16.+41.j 21.+46.j]
 [ 2.+27.j  7.+32.j 12.+37.j 17.+42.j 22.+47.j]
 [ 3.+28.j  8.+33.j 13.+38.j 18.+43.j 23.+48.j]
 [ 4.+29.j  9.+34.j 14.+39.j 19.+44.j 24.+49.j]]


To obtain the Hermitian conjugate of an array, simply transpose it and obtain the complex conjugate

In [69]:
A_dagger = A.T.conj()
print(A_dagger)

[[ 0.-25.j  5.-30.j 10.-35.j 15.-40.j 20.-45.j]
 [ 1.-26.j  6.-31.j 11.-36.j 16.-41.j 21.-46.j]
 [ 2.-27.j  7.-32.j 12.-37.j 17.-42.j 22.-47.j]
 [ 3.-28.j  8.-33.j 13.-38.j 18.-43.j 23.-48.j]
 [ 4.-29.j  9.-34.j 14.-39.j 19.-44.j 24.-49.j]]


### Exercise 05:
1. Use NumPy to create the three Pauli matrices $\sigma_x, \sigma_y, \sigma_z$ and show that the commutation relations $\left[\sigma_x, \sigma_y\right] = i \sigma_z$ and $\left[\sigma_z, \sigma_y\right] = -i \sigma_x$, hold true.
2. Create the following matrix and vector and multiply them in the usual matrix-vector way.
\begin{align*}
A & = \begin{pmatrix}
0 & 1 & 0 & 0\\
1 & 0 & 0 & 0\\
0 & 0 & 0 & 1\\
0 & 0 & 1 & 0
\end{pmatrix}\\
\vert{v}\rangle &= \begin{pmatrix}
1\\
-1\\
1\\
-1
\end{pmatrix}
\end{align*}
3. If a unitary transformation $U$ is given by
\begin{pmatrix}
0 & 0 & 0 & 1\\
0 & 0 & -1 & 0\\
0 & -1 & 0 & 0\\
1 & 0 & 0 & 0
\end{pmatrix},
then, compute the transformed matrix $A^\prime = UAU^T$ and vector $\vert{v^\prime}\rangle = U \vert{v}\rangle$. Show that $A^\prime\vert{v^\prime}\rangle = U\left(A\vert{v}\rangle\right)$.

### Reshaping arrays
Arrays can be reshaped with the new shape supplied as a tuple to the `.reshape` method. For instance, a $4 \times 4$ array can be reshaped into a $8 \times 2$ array as follows

In [70]:
A = np.random.random((4,4))
A

array([[0.84069924, 0.64703026, 0.59777741, 0.26041199],
       [0.18994634, 0.52849939, 0.00897515, 0.9019432 ],
       [0.86368425, 0.09460167, 0.42813314, 0.82839113],
       [0.05837961, 0.97256848, 0.32126456, 0.33003069]])

In [71]:
B = A.reshape(8,2)
B

array([[0.84069924, 0.64703026],
       [0.59777741, 0.26041199],
       [0.18994634, 0.52849939],
       [0.00897515, 0.9019432 ],
       [0.86368425, 0.09460167],
       [0.42813314, 0.82839113],
       [0.05837961, 0.97256848],
       [0.32126456, 0.33003069]])

In [72]:
C = A.reshape(2,8)
C

array([[0.84069924, 0.64703026, 0.59777741, 0.26041199, 0.18994634,
        0.52849939, 0.00897515, 0.9019432 ],
       [0.86368425, 0.09460167, 0.42813314, 0.82839113, 0.05837961,
        0.97256848, 0.32126456, 0.33003069]])

Arrays of any shape can be flattened to vectors in row-major order.

In [73]:
V = A.flatten()
V

array([0.84069924, 0.64703026, 0.59777741, 0.26041199, 0.18994634,
       0.52849939, 0.00897515, 0.9019432 , 0.86368425, 0.09460167,
       0.42813314, 0.82839113, 0.05837961, 0.97256848, 0.32126456,
       0.33003069])

### Computations on arrays

NumPy has special functions that can perform computations on arrays to yield numbers.

In [74]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [75]:
# Sums over all elements
np.sum(a)

np.int64(15)

In [76]:
# Multiplies all elements
np.prod(a)

np.int64(120)

These can be combined on the fly with scalar and array operations

In [77]:
print(a+1)
np.sum(a+1)

[2 3 4 5 6]


np.int64(20)

In [78]:
a = np.array([1,2,3,2,1])
b = np.array([2,3,4,5,4])

print(a @ b)
np.sum(a * b)

34


np.int64(34)

You can also perform operations on array slices. For instance:

In [79]:
M = np.arange(1, 10).reshape(3,3)
display(M)

display(M[1:3, 1:3])
s1 = np.sum(M[1:3, 1:3])
display(s1)

display(np.diag(M))
s2 = np.sum(np.diag(M))
display(s2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[5, 6],
       [8, 9]])

np.int64(28)

array([1, 5, 9])

np.int64(15)

In [80]:
# Averages (mean) and standard deviations (std) can also me computed
a = np.random.rand(4)
display(a)
display(np.mean(a))
display(np.std(a))

array([0.90884411, 0.79059717, 0.37751307, 0.14836048])

np.float64(0.556328706429691)

np.float64(0.30723034079284517)

In [81]:
# Note that random matrices of any shape can be created

a = np.random.rand(3,3)
display(a)

array([[0.52276935, 0.17598192, 0.53810864],
       [0.55390137, 0.09213119, 0.4503452 ],
       [0.55083919, 0.14823902, 0.78851179]])

In [82]:
# A random array with samples chosen from a Gaussian (Normal) distribution should yield close to zero mean and unit standard deviation
a = np.random.normal(size=10000)
a

array([-0.40334816,  2.10752773,  0.19685659, ...,  0.09281925,
       -0.75625539,  0.14583566])

In [83]:
np.mean(a), np.std(a)

(np.float64(-0.00742549613103598), np.float64(1.0094158460186864))

Finally, there are NumPy functions for computing determinants and traces of matrices. The determinant function is in the `np.linalg` submodule.

In [84]:
A = np.array([[1,2],
              [3,4]])

np.linalg.det(A)

np.float64(-2.0000000000000004)

In [85]:
np.trace(A)

np.int64(5)

### Exercise 06:

1. Use the `np.sum()` function to demonstrate the following relation for $N=5, 10, 20$
   \begin{equation*}
   \sum^N_{n=1} n^2 = \frac{1}{6}\;N\left(N+1\right)\left(2N+1\right)
   \end{equation*}
2. Create two random $5\times 5$ matrices $A,B$ and show that $\rm{Tr}\left[AB\right] = \rm{Tr}\left[BA\right]$.